pep_version: 2.0.0
sample_table: bedbuncher_query.csv

looper:
    output_dir: $BBTUTORIAL/outputs/bedbuncher_output/bedbuncher_pipeline_logs

sample_modifiers:
  append:
    pipeline_interfaces: $BBTUTORIAL/bedbuncher/pipeline_interface.yaml 
  derive:
    attributes: [bedbase_config]
    sources:
      source1: $BBTUTORIAL/bedbase/tutorial_files/{bbconfig_name}.yaml
