pep_version: 2.0.0
sample_table: bedstat_annotation_sheet.csv

looper:
    output-dir: $BEDBASE_DATA_PATH_HOST/outputs/bedmaker_output/bedmaker_pipeline_logs 

sample_modifiers:
  append:
    pipeline_interfaces: $BEDBASE_DATA_PATH_HOST/bedmaker/pipeline_interface.yaml
    input_file_path: INPUT
    output_file_path: OUTPUT
    output_bigbed_path: BBOUT
    narrowpeak: TRUE
    chrom_size:  CHROM_SIZE
  derive:
    attributes: [input_file_path, output_file_path, output_bigbed_path, chrom_size]
    sources:
      INPUT: "$BEDBASE_DATA_PATH_HOST/files/{file_name}"
      OUTPUT: "$BEDBASE_DATA_PATH_HOST/bed_files/{file_name}" 
      BBOUT: "$BEDBASE_DATA_PATH_HOST/bigbed_files/"
      CHROM_SIZE: "$BEDBASE_DATA_PATH_HOST/{genome}.chrom.sizes"
  imply:
    - if:
        antibody: [H3K4me3, H3K27me3, H3K27ac, H3K9ac, H4K5ac, H3K4me, H3K36me3, H4K5ac, H3K9ac]
      then:
        narrowpeak: FALSE
