pep_version: 2.0.0
sample_table: bedstat_annotation_sheet.csv

looper:
    output-dir: $BEDBASE_DATA_PATH_HOST/outputs/bedqc_output/bedqc_pipeline_logs 

sample_modifiers:
  append:
    pipeline_interfaces: $BEDBASE_DATA_PATH_HOST/bedqc/pipeline_interface.yaml
    input_file_path: INPUT
    output_dir: $BEDBASE_DATA_PATH_HOST/outputs/bedqc_output/bedqc_pipeline_logs
  derive:
    attributes: [input_file_path]
    sources:
      INPUT: "$BEDBASE_DATA_PATH_HOST/bed_files/{file_name}" 
      
