pep_version: 2.0.0
sample_table: bedstat_annotation_sheet.csv

looper:
  output-dir: $BBTUTORIAL/outputs/bedstat_output/bedstat_pipeline_logs 

sample_modifiers:
  append:
    bedbase_config: $BBTUTORIAL/bedbase/tutorial_files/bedbase_configuration.yaml
    pipeline_interfaces: $BBTUTORIAL/bedstat/pipeline_interface.yaml
    output_file_path: OUTPUT
    yaml_file: SAMPLE_YAML
    open_signal_matrix: MATRIX
  derive:
    attributes: [output_file_path, yaml_file, open_signal_matrix]
    sources:
      OUTPUT: "$BBTUTORIAL/bed_files/{file_name}" 
      SAMPLE_YAML: "$BBTUTORIAL/outputs/bedstat_output/bedstat_pipeline_logs/submission/{sample_name}_sample.yaml"
      MATRIX: "$BBTUTORIAL/openSignalMatrix_{genome}_percentile99_01_quantNormalized_round4d.txt.gz"
