path:
  pipeline_output_path: $BEDBOSS_OUTPUT_PATH
  bedstat_dir: bedstat_output
  bedbuncher_dir: $BEDBOSS_OUTPUT_PATH/bedbuncher_output
  remote_url_base: null
database:
  host: localhost
  port: 5432
  password: bedbasepassword
  user: postgres
  name: postgres
  dialect: postgresql
  driver: psycopg2
server:
  host: 0.0.0.0
  port: 8080