path:
  bedstat_output: $BBTUTORIAL/outputs/bedstat_output
  bedbuncher_output: $BBTUTORIAL/outputs/bedbuncher_output

database:
  host: localhost
  bed_table: bedfiles
  bedsets_table: bedsets

server:
  host: 0.0.0.0
  port: 8000
