pep_version: 2.0.0
sample_table: bedstat_annotation_sheet.csv

looper:
  output_dir: $GITHUB_WORKSPACE/outputs/bedstat_output

sample_modifiers:
  append:
    bedbase_config: $GITHUB_WORKSPACE/ci/cfg/config_min.yaml
    pipeline_interfaces: $GITHUB_WORKSPACE/ci/cfg/bedstat_piface.yaml
    output_file_path: OUTPUT
    yaml_file: SAMPLE_YAML
  derive:
    attributes: [output_file_path, yaml_file]
    sources:
      OUTPUT: "$GITHUB_WORKSPACE/ci/data/{file_name}"
      SAMPLE_YAML: "$GITHUB_WORKSPACE/outputs/bedstat_output/submission/{sample_name}.yaml"